version: "2"

linters:
  default: none
  enable:
    - revive
  settings:
    revive:
      rules:
        - name: file-length-limit
          arguments:
            - max: 100
              skipComments: true
              skipBlankLines: true
